services:
  frontend:
    build:
      context: ./BurgerOrderer
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

  kitchenview:
    build:
      context: ./kitchenview
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

networks:
  burger-network:
    driver: bridge
