services:
  frontend:
    build:
      context: ./BurgerOrderer
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

  kitchenview:
    build:
      context: ./kitchenview
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

  db:
    image: mysql:5.7
    container_name: MenuStoreContainer
    platform: linux/x86_64
    ports: 
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: burger
      MYSQL_DATABASE: db
    volumes:
       - my-db:/var/lib/mysql:rw
       - ./MenuStoreDB.sql:/docker-entrypoint-initdb.d/MenuStoreDB.sql

    networks:
      - burger-network  # Ensure db is on the same network

  phpmyadmin:
    image: linuxserver/phpmyadmin
    restart: always
    ports:
      - "8077:80"
    environment:
      ports: 8077:80
      #PMA_HOST: db  # Specify the database host
    networks:
      - burger-network  # Ensure phpMyAdmin is on the same network

volumes:
  my-db:

networks:
  burger-network:
    driver: bridge