services:
  backend:
    image: node:14 # Use an appropriate base image, like Node.js
    container_name: backend-container
    working_dir: /app
    volumes:
      - ./Backend:/app
    command: npm start # Adjust this command according to how the backend runs
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

  frontend:
    build:
      context: ./BurgerOrderer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    networks:
      - burger-network
    depends_on:
      - backend

  kitchenview:
    build:
      context: ./kitchenview
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network
    depends_on:
      - backend

  menustore:
    image: mysql:latest
    container_name: MenuStore
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: burger
      MYSQL_DATABASE: db
    networks:
      - burger-network

networks:
  burger-network:
    driver: bridge
