version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network

  frontend:
    build:
      context: ./BurgerOrderer/Frontend_ordering
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    networks:
      - burger-network
    depends_on:
      - backend

  kitchenview:
    build:
      context: ./kitchenview
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    networks:
      - burger-network
    depends_on:
      - backend

networks:
  burger-network:
    driver: bridge
