version: "3.8"

services:
  kitchenview:
    build:
      context: . # Build context is the current directory (kitchenview)
    ports:
      - "8082:80" # Expose kitchenview on port 8082 externally, map to port 80 internally (Nginx)
    volumes:
      - ./kitchenview:/usr/share/nginx/html # Map the kitchenview directory to the correct path in Nginx
    environment:
      NODE_ENV: production
